### ISSUE TITLE
Any instructions/ documentation on this?

### ISSUE THREAD

**Issue by petruut** [asssaf/inky-gallery#1]
I'd love to be able to drop files into a folder and then to set some parameters for a slide show - is this what your py does?

**Comment by asssaf** [comment]
By "drop files into a folder" do you mean a folder on the device or in the cloud?
If it's the former, there a bunch of examples for that including [an official one](https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/inky_frame/image_gallery).

This script just periodically downloads an image from a URL, and depending on what is serving that URL you can implement a gallery.
I'm using [frameserve](https://github.com/asssaf/frameserve) to serve an image from a google cloud storage bucket. It currently simply serves the latest image that was dropped into the bucket (although it can be enhanced to pick an image from the bucket at random).

Anyway, adding instructions is a good idea. Just need to find time to do it...
